blank_issues_enabled: false
contact_links:
  - name: Support question
    url: https://gumroad.com/library
    about: "If your license includes support, see your Gumroad library for the contact. If you'd like to discuss with the community, join our Discord server."
